name: Daniel Bashir
markdown: kramdown
baseurl: ""

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: dbashir@hmc.edu
  facebook:
  flickr:
  github: db7894
  instagram:
  linkedin: daniel-bashir
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter:
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/

permalink: /blog/:year/:month/:day/:title
